import type { Metadata } from "next";
import { Geist, Geist_Mono, Viaoda_Libre } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const getVioda = Viaoda_Libre({
  variable: "--font-vioda",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  style: ["normal"],
  fallback: ["sans-serif"],
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${getVioda.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
