import type { Metadata } from "next";
import { Roboto, Playwrite_DK_Loopet } from "next/font/google";
import "./globals.css";

export const roboto = Roboto({
  weight: '400',
  style: 'normal',
  display: 'swap',
  subsets: ['latin'],
});

export const playwrite = Playwrite_DK_Loopet({
  weight: '400',
  style: 'normal',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        {children}
      </body>
    </html>
  );
}
